name: CI

on: push

jobs:
  nvd_scan:
    uses: yetanalytics/workflow-nvd/.github/workflows/nvd-scan.yml@v1
    with:
      nvd-clojure-version: "3.3.0"
      classpath-command: "clojure -Spath -Adb-sqlite:db-postgres"
      nvd-config-filename: ".nvd/config.json"

  lint:
    uses: yetanalytics/workflow-linter/.github/workflows/linter.yml@v2024.08.01-SNAPSHOT
    with:
      lint-directories: "src/bench src/build src/db src/main src/test"

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - test-sqlite
          - test-postgres-11
          - test-postgres-12
          - test-postgres-13
          - test-postgres-14
          - test-postgres-15
          - test-postgres-16

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CI Environment
        uses: yetanalytics/action-setup-env@v1

      - name: Run Makefile Target ${{ matrix.target }}
        run: make ${{ matrix.target }}
